### ISSUE TITLE
Accordion Performance Fix

### ISSUE THREAD

**Issue by harmyderoman** [una-ui/una-ui#122]
https://github.com/una-ui/una-ui/blob/da02583fcdf838d9e52fc7c014c93b77ce3a54e2/packages/nuxt/src/runtime/components/elements/Accordion.vue#L63

Since all props remain the same for all of the items, it'll be reasonable to make picked props const. No need even to compute them.
```ts
const pickedProps = pickProps(props, ['reverse', 'icon', 'btn', 'label', 'leading', 'loading', 'loadingPlacement', 'una', 'trailing', 'leading', 'to', 'type', 'disabled'])

// TODO: optimized this one
function mergedProps(itemProps: NAccordionItemProps) {
  return Object.assign(pickedProps, itemProps)
}
```

**Comment by harmyderoman** [comment]
https://github.com/una-ui/una-ui/issues/87

**Comment by phojie** [comment]
@harmyderoman, could you please create a pull request for this? I really appreciate it. 🙏🏿

**Comment by harmyderoman** [comment]
@phojie to main?

**Comment by phojie** [comment]
@harmyderoman yes please

**Comment by harmyderoman** [comment]
@phojie https://github.com/una-ui/una-ui/pull/123

**Comment by phojie** [comment]
thanks @harmyderoman 🎊

**Comment by harmyderoman** [comment]
@phojie I appreciate your work. Nice contribution to the community!
