### ISSUE TITLE
feat: NSkeleton, add new component and preset

### ISSUE THREAD

**Issue by mnenie** [una-ui/una-ui#141]
### 🆒 Your use case

Hi! I want to contribute to this wonderful UI library
so, this is how I see the skeleton component. 

<img width="597" alt="Снимок экрана 2024-07-24 в 18 31 11" src="https://github.com/user-attachments/assets/dd17f22f-a0b6-4217-a95c-d94655f87ed0">

<img width="599" alt="Снимок экрана 2024-07-24 в 18 32 08" src="https://github.com/user-attachments/assets/e4b1be99-64e2-4f67-a828-1c3b1f943fee">

<img width="609" alt="Снимок экрана 2024-07-24 в 18 26 13" src="https://github.com/user-attachments/assets/36bfd354-f6a2-478e-9a77-70495a38f4f7">
<img width="578" alt="Снимок экрана 2024-07-24 в 18 26 20" src="https://github.com/user-attachments/assets/f7d0221b-0909-4607-a12a-2ce38d07e8af">
<img width="603" alt="Снимок экрана 2024-07-24 в 18 26 32" src="https://github.com/user-attachments/assets/6f85208a-53c1-4e83-84b7-c233187cddbc">

### 🆕 The solution you'd like

I can make a pr because I've already got it ready.

For now: 
- animation: animate-pulse
- shape prop: 'rectangle' | 'circle'

You have a cool idea and I hope for further contribution

**Comment by phojie** [comment]
@mnenie  Wow, this is great! Thanks for your time contributing to this project. 

Could you please create a PR with your work so that I can review it and push it to release as soon as possible? ✨

**Comment by phojie** [comment]
@Mnenie It's already merged and now live in production. I made a few changes. Thanks, nicely done. 🔥 

ref: https://unaui.com/components/skeleton

**Comment by mnenie** [comment]
> @mnenie It's already merged and now live in production. I made a few changes. Thanks, nicely done. 🔥
> 
> ref: https://unaui.com/components/skeleton

ok, thanks. I saw the changes and I agree with them, it looks cool 🔥🔥🔥
