### ISSUE TITLE
fix(NSelect): initial v-model item is always checked

### ISSUE THREAD

**Issue by killjoy1221** [una-ui/una-ui#166]
### 🐞 The bug

The initial ref value in NSelect always appears checked.

![image](https://github.com/user-attachments/assets/dfcbb468-39e8-4155-bee9-3b82fe64d538)

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-agj1iz?file=app.vue

### 🌈 Expected behavior

The default value should not have a check next to it when not selected.

**Comment by phojie** [comment]
Thanks @killjoy1221  for reporting this issue, will fix this ASAP 💯 .

**Comment by phojie** [comment]
@killjoy1221  resolves in https://github.com/una-ui/una-ui/releases/tag/v0.12.1-beta.1
