### ISSUE TITLE
fix(FormGroup): `class` is no longer inherited

### ISSUE THREAD

**Issue by killjoy1221** [una-ui/una-ui#202]
### 🐞 The bug

https://github.com/una-ui/una-ui/commit/81993eb301979ec3d1343267ae17ed308aa27a93 changed the `NFormGroupProps` type to extend `NLabelProps`, which includes a `class` attribute. `<NFormGroup>` does not handle it, so it is not passed to the element or inherited automatically.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-vatwi7?file=app.vue

### 🌈 Expected behavior

Input:
```vue
<NFormGroup class="flex-row">
```
Expected output:
```html
<div form-group="" class="flex-row"></div>
```

**Comment by phojie** [comment]
@killjoy1221 this is already fixed through this PR https://github.com/una-ui/una-ui/pull/203, but if you want to have more custom `form-group` you can always have through the combination of https://unaui.com/components/label + https://unaui.com/components/input component
