### ISSUE TITLE
feat(NDivider): add new component and preset config

### ISSUE THREAD

**Issue by phojie** [una-ui/una-ui#34]

**Comment by mnenie** [comment]
I can take it on myself.

So, I like the implementation of MUI (ref: https://mui.com/material-ui/react-divider/)

I think it will be a `Divider.vue` with orientation and align (for slot)

**Comment by phojie** [comment]
Go ahead mate @mnenie 🔥, will assign it to you 💯

**Comment by mnenie** [comment]
> Go ahead mate @mnenie 🔥, will assign it to you 💯

@phojie thank you very much for the invitation🤝💯💯

**Comment by phojie** [comment]
@mnenie, I sent you an invite to join this project. It’s too early, but you’ve made significant contributions, and I really appreciate it! 😃

I also sent you an invite to ZenHub, our project management tool. They’re also sponsoring this project by providing ZenHub for free 🚀

Keep rocking, man! You’ve done an awesome job! 🔥 🔥 🔥

**Comment by mnenie** [comment]
@phojie I appreciate it. 🔥

So, honestly, I rarely use discord 😃 but here: `mnenie?`

**Comment by phojie** [comment]
@mnenie sent you an invite on Discord. Our Discord is kind of new too. Sometimes it's better to communicate there instead of relying on GH notifications, for quicker and more efficient communication, it's okay—don't pressure yourself 😄

**Comment by mnenie** [comment]
> @mnenie sent you an invite on Discord. Our Discord is kind of new too. Sometimes it's better to communicate there instead of relying on GH notifications, for quicker and more efficient communication, it's okay—don't pressure yourself 😄

@phojie don't see an invitation to discord yet 😃 
so, thats my profile 
<img width="288" alt="Снимок экрана 2024-08-08 в 21 37 27" src="https://github.com/user-attachments/assets/a852de9b-19c8-4ee2-b714-f3a928031ec4">
