### ISSUE TITLE
fix: `ERROR  Cannot read properties of undefined (reading 'sys')`

### ISSUE THREAD

**Issue by khattaksd** [una-ui/una-ui#98]
### 🐞 The bug

Getting errors on startup

`ERROR  Cannot read properties of undefined (reading 'sys')`

Reproducible is stackblitz https://stackblitz.com/edit/nuxt-starter-z63dhn?file=package.json

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-z63dhn?file=package.json

### 🌈 Expected behavior

nuxt app should start without errors

**Comment by phojie** [comment]
Hello @khattaksd,

You did not install Typescript as your dependency,
Just install typescript and you're good to go ✨, 

```bash
npm i typescript -D
```

 I'm going to create a starter template soon, please ping me if it does not solve the issue. thanks!

**Comment by phojie** [comment]
You can refer to or use this starter template I made for `UnaUI` https://github.com/una-ui/starter.
